name: Zola Deploy to Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          # target branch
          PAGES_BRANCH: gh-pages
          # access token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The commit message
          COMMIT_MESSAGE: "Build site"
