name: Zola Deploy to Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # target branch
          PAGES_BRANCH: gh-pages
          # access token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
